apiVersion: v1
kind: Secret
metadata:
  name: spring-app-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA== # Need to give in base64 encoded.

# WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
# Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret.

# kubectl apply -f secret.yaml --namespace=customer-one
# kubectl get secrets --namespace=customer-one
# kubectl describe secret spring-app-secret --namespace=customer-one