apiVersion: v1 # Not apps/v1.
# type of resource: Service: acts as an abstract way to expose an application running on a set of Pods as a network service.
# Deployment vs Service
# Kubernetes Deployments manage the lifecycle and scaling of application instances (Pods),
#  while Services provide a stable network endpoint and load balancing for those Pods.
#  They perform different functions but work together to ensure application availability and connectivity.
kind: Service
metadata:
  # name to the service.
  name: spring-app-service
#  namespace: customer-one
spec:
  selector:
    # The Service looks for Pods whose metadata has the label app set to spring-boot-app.
    app: spring-app
  ports:
    # Assigns a human-readable name to this specific port mapping.
    - name: http
      # This is the port on which the service is exposed within the cluster (ClusterIP).
      # Other Pods in the cluster can reach the service using port 80.
      port: 80
      # Port on the container where Spring Boot application is actually listening.
      # Traffic hitting the service on port 80 will be forwarded to port 8080 in the corresponding Pods.
      targetPort: 8080
      #      nodePort: 30080
  type: NodePort
  # Setting the service type to NodePort - the service will be accessible externally on a static port on each worker node
  # Kubernetes automatically assigns this port - application reachable even outside the cluster.
  # Allow external traffic direct access to your application through the node’s IP address.
  # This setup is ideal for exposing your application without needing an external load balancer,
  #  particularly during development or in simpler cluster architectures

  # kubectl apply -f service.yaml
  # kubectl get services