# TODO 2: Add properties.
server:
  port: 8081
spring:
  application:
    name: distributed-tracing-service-two-demo
#  http:
#    codecs:
#      log-request-details: true

# Always sample requests (1.0 = 100%)
management:
  tracing:
    sampling:
      probability: 1.0

#logging:
#  level:
#    root: trace
